[package]
name = "trade_log-lib"
version = "0.1.0"
authors = ["Alex Afshar <contact@alexafshar.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
